### ISSUE TITLE
Logs Are Not Shown

### ISSUE THREAD

**Issue by ghost** [octarine-noise/BetterFoliage#123] opened 2017-04-06 12:25 UTC
No any logs aren't shown. please help. using minecraft 1.11.2 forge 2264.
![2017-04-06_15 24 08](https://cloud.githubusercontent.com/assets/24831406/24753958/23822040-1add-11e7-9745-c9dfed8194f2.png)
please help :( thanks.

**Comment by ghost** [comment] 2017-04-06 12:26
and it is my modpack, you can try it https://www.technicpack.net/modpack/magenji.968153

**Comment by ghost** [comment] 2017-04-06 18:51
omg, any feature of the mod is not working; how can i know whats wrong?

**Comment by octarine-noise** [comment] 2017-04-06 19:04
Sounds like a possible duplicate of #122

**Comment by ghost** [comment] 2017-04-06 19:08
ok i got it working without foamfix... :(

**Comment by asiekierka** [comment] 2017-04-07 17:12
I reviewed the source code for the hook in question, and indeed - I forgot that there's no way to get the ModelLoader instance from a TextureStitchEvent.Pre event. However, I believe the intended way to do *that* is to scan through the IModels loaded in the first pass (after preInit) and use that information in the second pass.

**Comment by octarine-noise** [comment] 2017-04-09 10:57
Fixed in 2.1.4

**Comment by ghost** [comment] 2017-04-09 10:58
yes i noticed it. thanks^^

**Closed as completed by octarine-noise** 2017-04-09 10:57 UTC
