### ISSUE TITLE
Issue with Rounded Logs in 2.1.4

### ISSUE THREAD

**Issue by Amaxter** [octarine-noise/BetterFoliage#124] opened 2017-04-09 18:09 UTC
https://goo.gl/RBk0nn

**Comment by MysticAura** [comment] 2017-07-06 15:45
I'm still having this problem on 2.16. 
MC: 1.12
Forge: 2397

It really would be an easy fix, so I hope it gets done soon. I know it's cosmetic, but cosmetics is what this mod is about. The log ends just need a texture adjustment and then this mod will be pretty much perfect

**Comment by octarine-noise** [comment] 2017-07-06 19:02
I'd love to have an answer for you guys, but this issue is driving me crazy. It _never_ does this for me, and if I can't reproduce it, I can't see what's wrong under the hood. And the fact that it keeps working fine for me (across all MC and Forge versions, in any modpack and with any resource pack) makes me think there's nothing wrong with my code _per se_, but it's something more esoteric (like OpenGL drivers, idk).

You might be able to help me narrow it down with a bit of Q&A (and testing).
- Do all logs look warped the exact same way? Vanilla and modded? Both endcaps?
- Do different log types have different "junk" on them, or are they the same?
- Does it happen consistently? With older MC and BF versions too?
- What kind of GPU do you have?

**Comment by QuImUfu** [comment] 2017-07-06 20:59
I can always reproduce.
This issue happens depending on the mipmapping setting:
mipmapping=off-3:
  western side:
  ![2017-07-06_21 33 28](https://user-images.githubusercontent.com/9885301/27929399-17a7d17c-6293-11e7-956e-72976256a27d.png)
  all other sides:
  ![2017-07-06_21 33 16](https://user-images.githubusercontent.com/9885301/27929411-24221980-6293-11e7-97ad-5c4247c4130e.png)
mipmapping=4:
  western side:
  ![2017-07-06_21 39 19](https://user-images.githubusercontent.com/9885301/27929530-abf556ba-6293-11e7-929a-5be1560a2d95.png)
  all other sides:
  ![2017-07-06_21 39 11](https://user-images.githubusercontent.com/9885301/27929558-b96125fe-6293-11e7-9050-66b40a900657.png)

It also does happen differently for different kinds of logs. The not bugged textures on the sides changes as it should, the bugged triangles seem to take textures from (seemingly) random places in the game, spruce wood has even two animated lava pixels and shows of the issue very well:
  western side:
  ![2017-07-06_21 49 11](https://user-images.githubusercontent.com/9885301/27929900-0ad70baa-6295-11e7-8861-b444116905ad.png)
  all other sides:
  ![2017-07-06_21 49 25](https://user-images.githubusercontent.com/9885301/27929911-0d428d74-6295-11e7-8beb-e8984d10dd5c.png)
It does happen consistently in the same configuration, restarts do not affect the look, it does look a little bit different in different versions of minecraft.

with old versions this doesn't happen, the bug (texture wise) was introduced somewhere in between 1.8.9-2.0.2 and 1.10.2-2.0.13 (i can look for the exact version the bug appeared first and whether there is a version completely without the bug, if you want me to)
this is how it looks in 1.8.9-2.0.2:
![2017-07-06_22 51 40](https://user-images.githubusercontent.com/9885301/27932350-c6e0d152-629d-11e7-8da1-ae88a357fed8.png)


about GPU and Driver:
GPU:
AMD RX 460
Driver:
```
name of display: :0.0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: X.Org (0x1002)
    Device: AMD POLARIS11 (DRM 3.9.0 / 4.10.0-26-generic, LLVM 4.0.1) (0x67ef)
    Version: 17.2.0
    Accelerated: yes
    Video memory: 2025MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL vendor string: X.Org
OpenGL renderer string: AMD POLARIS11 (DRM 3.9.0 / 4.10.0-26-generic, LLVM 4.0.1)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 17.2.0-devel
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.0 Mesa 17.2.0-devel
OpenGL shading language version string: 1.30
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.1 Mesa 17.2.0-devel
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
```
it does however also appear with the mesa software renderer, so that should be a way to reproduce the bug on all computers. (with the software renderer some of the triangles "flicker" between different textures)
It does not appear with the closed source nvidia drivers, however i think it is more likely a driver "feature" on nvidias side than a bug in all other drivers. 
Can also test with the closed AMD drivers both on Linux and Windows and the open nvidia drivers, if you want me to.
System:
Lubuntu 17.04, 64 bit using Linux 4.10.0-26

**Comment by octarine-noise** [comment] 2017-07-06 22:00
Wow, okay, some very nice info there. Thanks for taking the time to do this @QuImUfu!

You're definitely on to something here, as I'm using Windows and the closed nVidia drivers.

Regarding your last screenshot, the "correct" one: that's wrong too. It's the exact same bug, except the trash bits come from the right parts of the same texture, so it's not as noticeable. And I actually remember seeing that happen... like 1-2 times, sometime last year. So driver version may well be a factor. And now I'm starting to wonder how many people on different hardware are impacted, just didn't report it since they didn't realize they're seeing a bug.

It should look like this BTW, see how nicely octagonal and grid-aligned the logs are:

![correct](http://i.imgur.com/G4TZvCy.jpg)

I'd definitely like you to check the open nVidia drivers at least, possibly the others if you have time, it may shed light on some common theme.
The Mesa renderer is a very good idea, but since I can't find precompiled binaries anywhere, the process looks to be a PITA. Oh well...

**Comment by QuImUfu** [comment] 2017-07-06 22:29
jep, realized they are wrong later on as well, but only after testing with the closed nvidia drivers again, forgot to correct my post properly. :D
On windows the software renderer should be included in the libarys in [this](https://sourceforge.net/projects/msys2/files/REPOS/MINGW/i686/mingw-w64-i686-mesa-17.0.0-1-any.pkg.tar.xz/download) archive (7zip should be able to open it). Under most linux distros it is just a 
```
LIBGL_ALWAYS_SOFTWARE=1 java -jar ./minecraft.jar
```
away. Should even work on a live system from DVD, without changing anything on the system. (at least on ubuntu, you may have to "sudo apt install openjdk-8-jre" before)

Will test on all systems/configurations i can. May take a while. :D

**Comment by octarine-noise** [comment] 2017-07-06 22:50
Thanks for the link, didn't occur to me to check MinGW. That saved me a lot of headache.

You don't have to hurry, I'll be unavailable for a couple of days anyway. When I get back, I'll try that binary first, and if it fails I can still spin up a VM and install Linux on that. I'll need the software renderer anyway to test this, and that won't care about virtualization.

Let's science the shit out of this :)

**Comment by QuImUfu** [comment] 2017-07-07 08:45
sooo, did some testing:

Does the bug appear:

Linux | Nvidia | Intel | AMD
----|------|----|----
open  | no      | yes   | yes
closed| no      | N/A | yes

Windows | Nvidia | Intel | AMD
----|------|----|----
closed| no      | N/A | yes

I sadly have no PC running windows and having an Intel GPU and there are only open drivers for Intel gpus on linux.

**Comment by octarine-noise** [comment] 2017-07-10 16:00
Holy crap, strangest bug so far.

I managed to fire it up with the software renderer, and dug around a little. I found that the order I draw the vertices of the log endcaps matter.

If I draw them - like before - in the order (v1, v2, v3, v4) it looks good on nVidia, and broken on everything else.
If I shift them, and use the order (v2, v3, v4, v1), it looks broken on nVidia, and good on everything else.

Probably something to do with the way the GPU or the driver breaks up quads into triangles (they must use opposite diagonals for that), but I have no clue why that should matter, as all UV coordinates lie firmly inside the wood log texture.

Anyway, thanks again for your help @QuImUfu, couldn't have done it without you!

**Comment by octarine-noise** [comment] 2017-07-10 16:01
Someone with an affected GPU please check if the bug is resolved in 2.1.7. I don't want to close this until independent confirmation.

**Comment by MysticAura** [comment] 2017-07-10 17:51
Just tested the newest version. The bug appears to be resolved. I tried every level of mipmapping. As well as all different vid settings just to make sure.  My vid card is a Radeon R290x (just for the record).

Well done on the fix!

**Comment by QuImUfu** [comment] 2017-07-10 18:17
Resolved for all previously bugged configurations i can test.
Introduced the bug for the open nvidia driver, as nouveaus renderer info does not contain nvidia.
```
name of display: :0.0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: nouveau (0x10de)
    Device: NVD9 (0x1049)
    Version: 12.0.6
    Accelerated: yes
    Video memory: 1013MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.3
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL vendor string: nouveau
OpenGL renderer string: Gallium 0.4 on NVD9
OpenGL core profile version string: 4.3 (Core Profile) Mesa 12.0.6
OpenGL core profile shading language version string: 4.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.0 Mesa 12.0.6
OpenGL shading language version string: 1.30
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.1 Mesa 12.0.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10

```

**Comment by octarine-noise** [comment] 2017-07-10 18:30
Okay, I'll leave the issue open then so I don't forget. I'll move it to a config option in the next release, which defaults to the current vendor-check.

**Comment by octarine-noise** [comment] 2017-08-13 09:55
Configurable in 2.1.8

**Closed as completed by octarine-noise** 2017-08-13 09:55 UTC
