### ISSUE TITLE
Extra Leaves and Round Logs Issues

### ISSUE THREAD

**Issue by BLSK** [octarine-noise/BetterFoliage#70] opened 2016-06-24 03:12 UTC
MC v 1.9.4
Forge 1963

Leaves have what look like Bounding Boxes as seen in the first few pics granted some leaves I am not looking at and see it...noticeable in the 2nd picture just slightly off to the upper left:

Logs have what looks like Texture sharing I think or just slightly off its axis/scale in the pics further down
For most of the pictures I looked at Vanilla as it seems more relevant.

![2016-06-23_22 53 28](https://cloud.githubusercontent.com/assets/8443396/16326718/163e94ae-3997-11e6-8845-48d33ec449eb.png)
![2016-06-23_22 58 38](https://cloud.githubusercontent.com/assets/8443396/16326719/163e9562-3997-11e6-97c8-165bf812e9d7.png)

.
.
.
I tried different settings to see what the outcome was in the first few pics but then I decided to look at other logs so I could see if others were having the issue too

![2016-06-23_22 58 56](https://cloud.githubusercontent.com/assets/8443396/16326765/6f482a74-3997-11e6-8150-7ba0bff755fb.png)
![2016-06-23_23 00 40](https://cloud.githubusercontent.com/assets/8443396/16326767/6f4ac63a-3997-11e6-8090-9c332a9f697f.png)
![2016-06-23_23 02 14](https://cloud.githubusercontent.com/assets/8443396/16326766/6f496a88-3997-11e6-93a7-a7af166fb0bc.png)
![2016-06-23_23 03 11](https://cloud.githubusercontent.com/assets/8443396/16326769/6f4e7fd2-3997-11e6-80d5-e6420ce180b7.png)
![2016-06-23_23 03 15](https://cloud.githubusercontent.com/assets/8443396/16326768/6f4d0da0-3997-11e6-8485-3ea943f533e3.png)

**Comment by octarine-noise** [comment] 2016-07-23 15:57
I can't reproduce this right now. However, I know of the problem, it has cropped up intermittently before while I was testing. Seems completely random and rare, couldn't figure out why it happens.

Closing for now, but I'll keep it in mind.

**Closed as completed by octarine-noise** 2016-07-23 15:57 UTC
